# skaffold config file which is used to automate the workflow for building
# pushing and deploting applications to kubernates
# skaffold watches changes in the source code and when there is a change:
# builds the docker image, pushes them to registry, deploys to kubernates
apiVersion: skaffold/v4beta3
kind: Config
manifests: # tells skaffold to apply all the kubernates YAML files in this directory
  rawYaml:
    - ./infra/k8s/*
build: # builds the image locally and does not push to remote registy (for local developement)
  local:
    push: false
  artifacts: # tells how to build each service
    - image: rallycoding/auth # builds this docker image
      context: auth # looks in this folder for source code
      docker:
        dockerfile: Dockerfile # uses the docker file inside that folder
      sync: # tells skaffold if file in the src path changes, sync it to the container
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: rallycoding/tickets # builds this docker image
      context: tickets # looks in this folder for source code
      docker:
        dockerfile: Dockerfile # uses the docker file inside that folder
      sync: # tells skaffold if file in the src path changes, sync it to the container
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: rallycoding/orders # builds this docker image
      context: orders # looks in this folder for source code
      docker:
        dockerfile: Dockerfile # uses the docker file inside that folder
      sync: # tells skaffold if file in the src path changes, sync it to the container
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: rallycoding/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: rallycoding/expiration # builds this docker image
      context: expiration # looks in this folder for source code
      docker:
        dockerfile: Dockerfile # uses the docker file inside that folder
      sync: # tells skaffold if file in the src path changes, sync it to the container
        manual:
          - src: "src/**/*.ts"
            dest: .
