apiVersion: skaffold/v2alpha3
kind: Config # specifies the file is a skaffold configuration
deploy:
  kubectl: # specifies the kubernates command line tool that will be used (kubectl) for deployment
    manifests:
      - ./infra/k8s/* # skaffold will look for files in this directory
build: # build configuration for building the container
  local: # specifies the build will be local
    push: false # specified the image will not be pushed to docker hub (local developement and testing)
  artifacts: # defines the details for building container
    - image: jestinV/auth # name of the docker image to build
      context: ./auth # specifies the directory where the source code for the auth service resides
      docker:
        dockerfile: Dockerfile # points to the dockerfile for building the image
      sync: #Configures file synchronization for hot reloading during development.
        manual: # specified manual file synchronization rules
          - src: "src/**/*.ts" # Matches all  files in the  directory (and its subdirectories)
            dest: . # synchronizes matched files to root directory of the container
