apiVersion: apps/v1 # specifies the API version used for deployment
kind: Deployment # this is a deployment resource
metadata:
  name: auth-depl # assign the name to deployment resource
spec:
  replicas: 1 # specified one pod of the application should run
  selector:
    matchLabels:
      app: auth #match pods with the label to identify which pods are managed by this deployment
  template: # specififies how the pods will be created
    metadata:
      labels: # adds label to the pod
        app: auth
    spec:
      containers: # list the container(s) that will run inside the pod
        - name: auth #assigns name to the container
          image: jestinV/auth #specifies the docker image to use for this container
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service # defines how to expose the deployment (pods) to allow communication
metadata:
  name: auth-srv # assign the name to the service
spec:
  selector:
    app: auth # targets pod with the label to identify which pods to route traffic to
  ports:
    - name: auth # names port definition
      protocol: TCP # specified that TCP used for communication
      port: 3000 # exposes the service on port
      targetPort: 3000 # routes traffic to port 3000 on target pod
